### ISSUE TITLE
Environmental data

### ISSUE THREAD

**Issue by sylvainschmitt** [Bioforest-project/environment#1]

**Comment by sylvainschmitt** [comment]
- [x] Retrieve data for all available sites
- [x] Add sites
- [x] _Explore other climatic indices ?_
- [x] Fix BAFOG and Paracou extraction from SoilGrids
- [x] Explore Lesong, Malinau, Missiones, Sungai Lalang, Tené, Ulu Muda, and Uppangala issue with TMF

**Comment by mithilaunkule** [comment]
@sylvainschmitt Should we contact the site PIs that have their plot locations outside forest areas? I can ask them to re-check the co-ordinates

**Comment by sylvainschmitt** [comment]
@mithilaunkule , let me explore the problem more in depth first. You can focus on inventory and species raw data first please.

**Comment by sylvainschmitt** [comment]
>  Explore Lesong, Malinau, Missiones, Sungai Lalang, Tené, Ulu Muda, and Uppangala issue with TMF

According to last commit "environment 0.1.0.9010: esri wolrd imagery in site map for manual inspection of landscape, #1" and manual inspections:

- Lesong: in forest
- Malinau: most are in forest (e.g. CNV06 is dubious)
- Missiones: in forest
- Sungai Lalang: in forest
- Tené: in forest
- Ulu Muda: in forest
- Uppangala: in forest

So the issue must come from TMF extraction.

**Comment by sylvainschmitt** [comment]
> > Explore Lesong, Malinau, Missiones, Sungai Lalang, Tené, Ulu Muda, and Uppangala issue with TMF
> 
> According to last commit "environment 0.1.0.9010: esri wolrd imagery in site map for manual inspection of landscape, #1" and manual inspections:
> 
>     * Lesong: in forest
> 
>     * Malinau: most are in forest (e.g. CNV06 is dubious)
> 
>     * Missiones: in forest
> 
>     * Sungai Lalang: in forest
> 
>     * Tené: in forest
> 
>     * Ulu Muda: in forest
> 
>     * Uppangala: in forest
> 
> 
> So the issue must come from TMF extraction.

The issue was coming from the fake 'time" variable from xee extraction with data not always in the second layer: https://github.com/Bioforest-project/environment/blob/c0d6c5c754cf01470b678539e57c2f9c0bcc9e9b/scripts/get_landscape.py#L37-L43

The code could be improved with a loop.

**Comment by sylvainschmitt** [comment]
Misiones is simply outside of TMF!

**Comment by sylvainschmitt** [comment]
I added the use of a bounding bow to fix soil data extraction for Paracou and Bafog:
https://github.com/Bioforest-project/environment/blob/417fb7faec5e1cee42f356efcb72e14c115b22fc/scripts/get_soil.py#L23-L25

I don't really know what was going wrong but it's working now.
